# Generated by Django 4.1.1 on 2022-09-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.address'),
        ),
    ]
