# Generated by Django 4.1.1 on 2022-09-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_house_address_address_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='promotions',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
