# Generated by Django 4.1.1 on 2022-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_customer_house_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
