# Generated by Django 4.1.1 on 2022-09-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_house_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/images')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.house')),
            ],
        ),
    ]
