# Generated by Django 4.1.1 on 2022-09-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_houseimage_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
